import { twClass } from "../../lib/tw";
import { useEffect, useState } from "react";
import { Check, Clock3, MapPin, MessageCircle, ShieldCheck, UserRound, X } from "lucide-react";
import { Link } from "react-router";
import { fileUrl, jobsApi } from "../../lib/api";
import { toast } from "sonner";

type Job={_id:string;title:string;date:string;district?:string;taluka?:string;locality?:string;workersNeeded:number;categoryName?:string;applications?:any[]};
export default function CustomerRequestsPage(){
 const [jobs,setJobs]=useState<Job[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);try{const r=await jobsApi.mine();setJobs((r.jobs||[]) as Job[]);}catch(e){toast.error(e instanceof Error?e.message:"Unable to load worker requests");}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const update=async(id:string,status:"accepted"|"rejected")=>{setBusy(id);try{await jobsApi.updateApplication(id,status);toast.success(status==="accepted"?"Worker accepted and booking created":"Worker request rejected");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update request");}finally{setBusy("")}};
 return <div className={twClass('wf-page')}><div className={twClass('wf-wide')}><section className={twClass('wf-page-hero')}><div><span className={twClass('wf-kicker')}><UserRound/> WORKFORCE REQUESTS</span><h1>Worker Requests</h1><p>Review workers who applied to your requirements.</p></div><Link to="/post-requirement" className={twClass('wf-outline-btn')}>Post Requirement</Link></section>
 {loading?<div className={twClass('wf-empty')}>Loading requests…</div>:!jobs.length?<div className={twClass('wf-empty')}>No requirements posted yet.</div>:<div className={twClass('grid gap-4')}>{jobs.map(job=><section key={job._id} className={twClass('wf-panel p-4 sm:p-5')}><div className={twClass('flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between')}><div><h2 className={twClass('text-base font-black text-[#123d64]')}>{job.title}</h2><p className={twClass('mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500')}><span>{job.categoryName||"Work"}</span><span>·</span><span><MapPin className={twClass('inline')} size={12}/> {[job.locality,job.taluka,job.district].filter(Boolean).join(", ")||"Location not specified"}</span><span>·</span><span>{new Date(job.date).toLocaleDateString()}</span></p></div><span className={twClass('rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black text-slate-600')}>{job.applications?.length||0} requests</span></div>
 <div className={twClass('mt-4 grid gap-3')}>{(job.applications||[]).map((a:any)=><article key={a._id} className={twClass('rounded-2xl border border-slate-200 bg-white p-3')}><div className={twClass('flex flex-col gap-3 sm:flex-row sm:items-center')}><img className={twClass('h-14 w-14 shrink-0 rounded-xl object-cover')} src={fileUrl(a.worker?.profileImage)||"/worker-carpenter.jpg"} onError={e=>{e.currentTarget.src="/worker-carpenter.jpg"}} alt=""/><div className={twClass('min-w-0 flex-1')}><div className={twClass('flex flex-wrap items-center gap-2')}><b className={twClass('text-sm text-slate-900')}>{a.worker?.name||"Worker"}</b><span className={twClass('inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700')}><ShieldCheck size={11}/> Verified worker</span><span className={twClass(`rounded-full px-2 py-1 text-[9px] font-black capitalize ${a.status==="accepted"?"bg-emerald-100 text-emerald-700":a.status==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`)}>{a.status}</span></div><p className={twClass('mt-1 text-xs text-slate-500')}>Message: {a.note||"No message added."}</p></div>{a.status==="pending"&&<div className={twClass('grid grid-cols-2 gap-2 sm:w-52')}><button disabled={busy===a._id} onClick={()=>void update(a._id,"accepted")} className={twClass('inline-flex items-center justify-center gap-1 rounded-xl bg-emerald-600 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50')}><Check size={14}/> Accept</button><button disabled={busy===a._id} onClick={()=>void update(a._id,"rejected")} className={twClass('inline-flex items-center justify-center gap-1 rounded-xl border border-red-200 bg-red-50 px-3 py-2.5 text-xs font-black text-red-700 disabled:opacity-50')}><X size={14}/> Reject</button></div>}{a.status==="accepted"&&<Link to={`/messages?worker=${a.worker?._id||a.worker}`} className={twClass('inline-flex items-center justify-center gap-1 rounded-xl bg-emerald-600 px-3 py-2.5 text-xs font-black text-white')}><MessageCircle size={14}/> Chat with Work Buddy</Link>}</div></article>)}{!job.applications?.length&&<div className={twClass('rounded-xl border border-dashed border-slate-200 p-6 text-center text-xs text-slate-400')}><Clock3 className={twClass('mx-auto mb-2')} size={18}/>Waiting for worker requests.</div>}</div></section>)}</div>}
 </div></div>;
}
