import { twClass } from "../../lib/tw";
import { useEffect, useMemo, useState } from "react";
import { Check, Download, Eye, FileText, Search, ShieldAlert, X } from "lucide-react";
import { adminApi, fileUrl } from "../../lib/api";
import { toast } from "sonner";

type Status="pending"|"approved"|"rejected";

export default function AdminVerification(){
 const [workers,setWorkers]=useState<any[]>([]); const [docs,setDocs]=useState<any[]>([]); const [q,setQ]=useState(""); const [status,setStatus]=useState<Status>("pending"); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [w,d]=await Promise.all([adminApi.workers(status),adminApi.verificationDocuments(status)]);setWorkers(w.workers||[]);setDocs(d.documents||[]);}catch(e){toast.error(e instanceof Error?e.message:"Unable to load verification data");}finally{setLoading(false)}};
 useEffect(()=>{void load()},[status]);
 const filtered=useMemo(()=>workers.filter(w=>`${w.user?.name||""} ${w.user?.email||""} ${w.headline||""} ${w.city||""} ${w.area||""}`.toLowerCase().includes(q.toLowerCase())),[workers,q]);
 const setWorkerStatus=async(id:string,next:Status)=>{let reason="";if(next==="rejected"){reason=window.prompt("Enter rejection reason")?.trim()||"";if(!reason)return;}try{await adminApi.updateWorkerVerification(id,next,reason);toast.success(`Worker ${next}`);await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update worker verification")}};
 const docStatus=async(id:string,next:"approved"|"rejected")=>{let note="";if(next==="rejected"){note=window.prompt("Enter rejection reason")?.trim()||"";if(!note)return;}try{await adminApi.updateVerification(id,next,note);toast.success(`Document ${next}`);await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update document")}};
 const fetchDoc=async(id:string)=>{const token=localStorage.getItem("workforce_token");const base=(import.meta.env.VITE_API_URL||"http://localhost:5000/api").replace(/\/$/,"");const r=await fetch(`${base}/admin/verification/${id}/file`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error("Document unavailable");return {blob:await r.blob(),name:r.headers.get("content-disposition")?.match(/filename="?([^";]+)"?/i)?.[1]||"verification-document"};};
 const viewDoc=async(id:string)=>{try{const {blob}=await fetchDoc(id);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){toast.error(e instanceof Error?e.message:"Unable to open document")}};
 const downloadDoc=async(id:string)=>{try{const {blob,name}=await fetchDoc(id);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast.error(e instanceof Error?e.message:"Unable to download document")}};
 return <div className={twClass('space-y-5')}><div className={twClass('flex flex-col gap-4 rounded-2xl border border-[#dce9f3] bg-white p-5 shadow-sm lg:flex-row lg:items-end lg:justify-between')}><div><p className={twClass('text-xs font-black uppercase tracking-[.15em] text-[#148bc8]')}>Worker verification</p><h1 className={twClass('mt-1 text-2xl font-black text-[#10355d]')}>Review workers</h1><p className={twClass('mt-1 text-sm text-slate-500')}>Review the worker selfie and submitted verification documents before granting Worker access.</p></div><div className={twClass('flex flex-col gap-2 sm:flex-row')}><div className={twClass('relative w-full sm:w-72')}><Search className={twClass('absolute left-3 top-3 text-slate-400')} size={16}/><input className={twClass('h-10 w-full rounded-xl border border-[#dce9f3] bg-[#f8fbfd] pl-9 pr-3 text-sm outline-none focus:border-[#1595dc]')} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search workers..."/></div><div className={twClass('flex gap-1 rounded-xl bg-[#f1f7fb] p-1')}>{(["pending","approved","rejected"] as Status[]).map(v=><button key={v} type="button" onClick={()=>setStatus(v)} className={status===v?"rounded-lg bg-white px-3 py-2 text-[11px] font-black text-[#127fbd] shadow-sm":"rounded-lg px-3 py-2 text-[11px] font-bold capitalize text-slate-500"}>{v}</button>)}</div></div></div>
 <div className={twClass('grid gap-4')}>{loading?<div className={twClass('rounded-2xl border border-[#dce9f3] bg-white p-10 text-center text-sm text-slate-400')}>Loading verification records...</div>:filtered.map(w=>{const workerId=String(w.user?._id||w.user||w._id);const workerDocs=docs.filter(d=>String(d.worker?._id||d.worker)===workerId);return <article key={w._id} className={twClass('overflow-hidden rounded-2xl border border-[#dce9f3] bg-white shadow-sm')}><div className={twClass('flex flex-col gap-5 p-5 lg:flex-row lg:items-start lg:justify-between')}><div className={twClass('flex min-w-0 gap-4')}><img src={fileUrl(w.user?.profileImage)||"/workforce-logo.png"} className={twClass('h-16 w-16 shrink-0 rounded-2xl border border-slate-200 object-cover')} alt="Worker selfie"/><div className={twClass('min-w-0')}><div className={twClass('flex flex-wrap items-center gap-2')}><h2 className={twClass('font-black text-[#12385f]')}>{w.user?.name||"Worker"}</h2><span className={twClass(`rounded-full px-2.5 py-1 text-[10px] font-black capitalize ${w.verificationStatus==="approved"?"bg-emerald-100 text-emerald-700":w.verificationStatus==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`)}>{w.verificationStatus}</span></div><p className={twClass('mt-1 text-sm text-slate-500')}>{w.headline||"Profession not provided"} · {w.experienceYears||0} years</p><p className={twClass('mt-1 text-xs text-slate-400')}>{[w.city,w.area,w.taluka,w.district].filter(Boolean).join(" · ")||"Location not provided"}</p><p className={twClass('mt-2 text-xs text-slate-500')}>Skills: {(w.skillNames||[]).join(", ")||"None provided"}</p><p className={twClass('mt-2 text-[10px] font-bold text-[#148bc8]')}>Selfie is the worker's verified profile photo.</p></div></div><div className={twClass('flex flex-wrap gap-2')}><button onClick={()=>void setWorkerStatus(workerId,w.verificationStatus==="approved"?"pending":"approved")} className={twClass('inline-flex items-center gap-1.5 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white')}><Check size={14}/>{w.verificationStatus==="approved"?"Move to pending":"Approve worker"}</button><button onClick={()=>void setWorkerStatus(workerId,"rejected")} className={twClass('inline-flex items-center gap-1.5 rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700')}><X size={14}/>Reject</button></div></div>
 <div className={twClass('border-t border-[#e8f0f5] bg-[#fbfdff] p-5')}><div className={twClass('flex items-center justify-between gap-3')}><div><p className={twClass('text-xs font-black text-[#173b60]')}>Verification documents</p><p className={twClass('mt-0.5 text-[10px] text-slate-400')}>Aadhaar / ID is required. Experience certificate is optional.</p></div><span className={twClass('rounded-full bg-white px-2.5 py-1 text-[10px] font-black text-slate-500')}>{workerDocs.length} file(s)</span></div><div className={twClass('mt-3 grid gap-3 sm:grid-cols-2')}>{workerDocs.map(d=><div key={d._id} className={twClass('rounded-xl border border-[#dce9f3] bg-white p-3')}><div className={twClass('flex items-center gap-2')}><FileText size={17} className={twClass('text-[#1684d1]')}/><span className={twClass('min-w-0 flex-1 truncate text-xs font-bold text-[#173b60]')}>{d.fileName}</span><span className={twClass(`rounded-full px-2 py-0.5 text-[9px] font-black ${d.status==="approved"?"bg-emerald-50 text-emerald-700":d.status==="rejected"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`)}>{d.status}</span></div><p className={twClass('mt-1 text-[10px] uppercase text-slate-400')}>{d.type==="id"?"Aadhaar / ID":"Experience certificate"}</p><div className={twClass('mt-3 flex flex-wrap gap-2')}><button onClick={()=>void viewDoc(d._id)} className={twClass('inline-flex items-center gap-1 text-[10px] font-black text-[#1285c7]')}><Eye size={13}/>View</button><button onClick={()=>void downloadDoc(d._id)} className={twClass('inline-flex items-center gap-1 text-[10px] font-black text-[#1285c7]')}><Download size={13}/>Download</button>{d.status!=="approved"&&<button onClick={()=>void docStatus(d._id,"approved")} className={twClass('text-[10px] font-black text-emerald-700')}>Approve</button>}{d.status!=="rejected"&&<button onClick={()=>void docStatus(d._id,"rejected")} className={twClass('text-[10px] font-black text-red-700')}>Reject</button>}</div></div>)}{!workerDocs.length&&<div className={twClass('flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800')}><ShieldAlert size={16}/> No verification documents found for this worker.</div>}</div></div></article>})}{!loading&&!filtered.length&&<div className={twClass('rounded-2xl border border-[#dce9f3] bg-white p-10 text-center text-sm text-slate-400')}>No workers found.</div>}</div></div>;
}
